// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_system_5fprotocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_system_5fprotocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_system_5fprotocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_system_5fprotocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_system_5fprotocol_2eproto;
namespace protocal {
class RobotEvent;
struct RobotEventDefaultTypeInternal;
extern RobotEventDefaultTypeInternal _RobotEvent_default_instance_;
}  // namespace protocal
PROTOBUF_NAMESPACE_OPEN
template<> ::protocal::RobotEvent* Arena::CreateMaybeMessage<::protocal::RobotEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protocal {

// ===================================================================

class RobotEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocal.RobotEvent) */ {
 public:
  inline RobotEvent() : RobotEvent(nullptr) {}
  ~RobotEvent() override;
  explicit constexpr RobotEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RobotEvent(const RobotEvent& from);
  RobotEvent(RobotEvent&& from) noexcept
    : RobotEvent() {
    *this = ::std::move(from);
  }

  inline RobotEvent& operator=(const RobotEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline RobotEvent& operator=(RobotEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RobotEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const RobotEvent* internal_default_instance() {
    return reinterpret_cast<const RobotEvent*>(
               &_RobotEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RobotEvent& a, RobotEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(RobotEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RobotEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RobotEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RobotEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RobotEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RobotEvent& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RobotEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocal.RobotEvent";
  }
  protected:
  explicit RobotEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventSentFieldNumber = 2,
    kRobotIDFieldNumber = 1,
  };
  // optional string eventSent = 2;
  bool has_eventsent() const;
  private:
  bool _internal_has_eventsent() const;
  public:
  void clear_eventsent();
  const std::string& eventsent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_eventsent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_eventsent();
  PROTOBUF_NODISCARD std::string* release_eventsent();
  void set_allocated_eventsent(std::string* eventsent);
  private:
  const std::string& _internal_eventsent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_eventsent(const std::string& value);
  std::string* _internal_mutable_eventsent();
  public:

  // int32 robotID = 1;
  void clear_robotid();
  int32_t robotid() const;
  void set_robotid(int32_t value);
  private:
  int32_t _internal_robotid() const;
  void _internal_set_robotid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protocal.RobotEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr eventsent_;
  int32_t robotid_;
  friend struct ::TableStruct_system_5fprotocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RobotEvent

// int32 robotID = 1;
inline void RobotEvent::clear_robotid() {
  robotid_ = 0;
}
inline int32_t RobotEvent::_internal_robotid() const {
  return robotid_;
}
inline int32_t RobotEvent::robotid() const {
  // @@protoc_insertion_point(field_get:protocal.RobotEvent.robotID)
  return _internal_robotid();
}
inline void RobotEvent::_internal_set_robotid(int32_t value) {
  
  robotid_ = value;
}
inline void RobotEvent::set_robotid(int32_t value) {
  _internal_set_robotid(value);
  // @@protoc_insertion_point(field_set:protocal.RobotEvent.robotID)
}

// optional string eventSent = 2;
inline bool RobotEvent::_internal_has_eventsent() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RobotEvent::has_eventsent() const {
  return _internal_has_eventsent();
}
inline void RobotEvent::clear_eventsent() {
  eventsent_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RobotEvent::eventsent() const {
  // @@protoc_insertion_point(field_get:protocal.RobotEvent.eventSent)
  return _internal_eventsent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RobotEvent::set_eventsent(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 eventsent_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocal.RobotEvent.eventSent)
}
inline std::string* RobotEvent::mutable_eventsent() {
  std::string* _s = _internal_mutable_eventsent();
  // @@protoc_insertion_point(field_mutable:protocal.RobotEvent.eventSent)
  return _s;
}
inline const std::string& RobotEvent::_internal_eventsent() const {
  return eventsent_.Get();
}
inline void RobotEvent::_internal_set_eventsent(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  eventsent_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RobotEvent::_internal_mutable_eventsent() {
  _has_bits_[0] |= 0x00000001u;
  return eventsent_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RobotEvent::release_eventsent() {
  // @@protoc_insertion_point(field_release:protocal.RobotEvent.eventSent)
  if (!_internal_has_eventsent()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = eventsent_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (eventsent_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    eventsent_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void RobotEvent::set_allocated_eventsent(std::string* eventsent) {
  if (eventsent != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  eventsent_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), eventsent,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (eventsent_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    eventsent_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protocal.RobotEvent.eventSent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocal

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_system_5fprotocol_2eproto
