// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_protocol.proto

#include "system_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace protocal {
constexpr RobotEvent::RobotEvent(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : eventsent_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , robotid_(0){}
struct RobotEventDefaultTypeInternal {
  constexpr RobotEventDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~RobotEventDefaultTypeInternal() {}
  union {
    RobotEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT RobotEventDefaultTypeInternal _RobotEvent_default_instance_;
}  // namespace protocal
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_system_5fprotocol_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_system_5fprotocol_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_system_5fprotocol_2eproto = nullptr;

const uint32_t TableStruct_system_5fprotocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protocal::RobotEvent, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protocal::RobotEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protocal::RobotEvent, robotid_),
  PROTOBUF_FIELD_OFFSET(::protocal::RobotEvent, eventsent_),
  ~0u,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::protocal::RobotEvent)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protocal::_RobotEvent_default_instance_),
};

const char descriptor_table_protodef_system_5fprotocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025system_protocol.proto\022\010protocal\"C\n\nRob"
  "otEvent\022\017\n\007robotID\030\001 \001(\005\022\026\n\teventSent\030\002 "
  "\001(\tH\000\210\001\001B\014\n\n_eventSentb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_system_5fprotocol_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_system_5fprotocol_2eproto = {
  false, false, 110, descriptor_table_protodef_system_5fprotocol_2eproto, "system_protocol.proto", 
  &descriptor_table_system_5fprotocol_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_system_5fprotocol_2eproto::offsets,
  file_level_metadata_system_5fprotocol_2eproto, file_level_enum_descriptors_system_5fprotocol_2eproto, file_level_service_descriptors_system_5fprotocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_system_5fprotocol_2eproto_getter() {
  return &descriptor_table_system_5fprotocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_system_5fprotocol_2eproto(&descriptor_table_system_5fprotocol_2eproto);
namespace protocal {

// ===================================================================

class RobotEvent::_Internal {
 public:
  using HasBits = decltype(std::declval<RobotEvent>()._has_bits_);
  static void set_has_eventsent(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

RobotEvent::RobotEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:protocal.RobotEvent)
}
RobotEvent::RobotEvent(const RobotEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  eventsent_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    eventsent_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_eventsent()) {
    eventsent_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_eventsent(), 
      GetArenaForAllocation());
  }
  robotid_ = from.robotid_;
  // @@protoc_insertion_point(copy_constructor:protocal.RobotEvent)
}

inline void RobotEvent::SharedCtor() {
eventsent_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  eventsent_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
robotid_ = 0;
}

RobotEvent::~RobotEvent() {
  // @@protoc_insertion_point(destructor:protocal.RobotEvent)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void RobotEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  eventsent_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RobotEvent::ArenaDtor(void* object) {
  RobotEvent* _this = reinterpret_cast< RobotEvent* >(object);
  (void)_this;
}
void RobotEvent::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RobotEvent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void RobotEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:protocal.RobotEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    eventsent_.ClearNonDefaultToEmpty();
  }
  robotid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RobotEvent::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 robotID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          robotid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string eventSent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_eventsent();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protocal.RobotEvent.eventSent"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RobotEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocal.RobotEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 robotID = 1;
  if (this->_internal_robotid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_robotid(), target);
  }

  // optional string eventSent = 2;
  if (_internal_has_eventsent()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_eventsent().data(), static_cast<int>(this->_internal_eventsent().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocal.RobotEvent.eventSent");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_eventsent(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocal.RobotEvent)
  return target;
}

size_t RobotEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocal.RobotEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string eventSent = 2;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_eventsent());
  }

  // int32 robotID = 1;
  if (this->_internal_robotid() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_robotid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RobotEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    RobotEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RobotEvent::GetClassData() const { return &_class_data_; }

void RobotEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<RobotEvent *>(to)->MergeFrom(
      static_cast<const RobotEvent &>(from));
}


void RobotEvent::MergeFrom(const RobotEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocal.RobotEvent)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_eventsent()) {
    _internal_set_eventsent(from._internal_eventsent());
  }
  if (from._internal_robotid() != 0) {
    _internal_set_robotid(from._internal_robotid());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RobotEvent::CopyFrom(const RobotEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocal.RobotEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotEvent::IsInitialized() const {
  return true;
}

void RobotEvent::InternalSwap(RobotEvent* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &eventsent_, lhs_arena,
      &other->eventsent_, rhs_arena
  );
  swap(robotid_, other->robotid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RobotEvent::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_system_5fprotocol_2eproto_getter, &descriptor_table_system_5fprotocol_2eproto_once,
      file_level_metadata_system_5fprotocol_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocal
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protocal::RobotEvent* Arena::CreateMaybeMessage< ::protocal::RobotEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocal::RobotEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
